global using Microsoft.EntityFrameworkCore;
global using MoviesApi.Data;
global using MoviesApi.Models;
global using MoviesApi.DTOs.Genre;
global using MoviesApi.DTOs.Movie;
global using MoviesApi.Interfaces;
global using MoviesApi.Repositories;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;